name: Golangci Lint Check

on:
    push:
        branches:
            - "master"
            - "main"
        paths-ignore:
            - "**.md"
            - LICENSE
            - ".github/ISSUE_TEMPLATE/*.yml"
            - ".github/dependabot.yml"
    pull_request:
        branches:
            - "*"
        paths-ignore:
            - "**.md"
            - LICENSE
            - ".github/ISSUE_TEMPLATE/*.yml"
            - ".github/dependabot.yml"

jobs:
    golangci-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch Repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.x'

            - name: Install golangci-lint
              run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2

            - name: Get directories to lint
              run: |
                  REPO_ROOT=$(pwd)
                  go list -f '{{.Dir}}' -m > dirs.txt
                  sed -i "s|${REPO_ROOT}/||" dirs.txt
                  cat dirs.txt

            - name: Run golangci-lint for each directory
              run: |
                  while IFS= read -r dir; do
                    echo "Linting directory $dir"
                    (cd "$dir" && golangci-lint run --tests=false)
                  done < dirs.txt
