name: Gosec Security Scan

on:
  push:
    branches:
      - "master"
      - "main"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"

jobs:
  gosec-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'oldstable'
          check-latest: true
          cache: false
      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec (paseto)
        working-directory: ./paseto
        run: gosec -exclude-dir=internal ./...
        # -----
      - name: Run Gosec (fiberzap)
        working-directory: ./fiberzap
        run: gosec -exclude-dir=internal ./...
        # -----
      - name: Run Gosec (otelfiber)
        working-directory: ./otelfiber
        run: gosec -exclude-dir=example ./...
      - name: Run Gosec (swagger)
        working-directory: ./swagger
        run: gosec -exclude-dir=internal ./...
        # -----
      - name: Run Gosec (casbin)
        working-directory: ./casbin
        run: gosec -exclude-dir=internal ./...
        # -----
      - name: Run Gosec (fibernewrelic)
        working-directory: ./fibernewrelic
        run: gosec -exclude-dir=internal ./...
        # -----
      - name: Run Gosec (opafiber)
        working-directory: ./opafiber
        run: gosec -exclude-dir=internal ./...
        # -----
      - name: Run Gosec (fiberi18n)
        working-directory: ./fiberi18n
        run: gosec -exclude-dir=internal ./...
        # -----
      - name: Run Gosec (fiberzerolog)
        working-directory: ./fiberzerolog
        run: gosec -exclude-dir=internal ./...
        # -----
      - name: Run Gosec (jwt)
        working-directory: ./jwt
        run: gosec -exclude-dir=internal ./...
        # -----
      - name: Run Gosec (websocket)
        working-directory: ./websocket
        run: gosec -exclude-dir=internal ./...
        # -----
      - name: Run Gosec (fgprof)
        working-directory: ./fgprof
        run: gosec -exclude-dir=internal ./...
        # -----